### ISSUE TITLE
When deserializing, floating point numbers will be converted into integers.

### ISSUE THREAD

**Issue by zdh-github** [Eljoy/ts-jackson#3]
Hello, I'm from China. I like this library very much. Although this BUG has little impact, I hope you can take the time to fix it. Thanks!

**Comment by Eljoy** [comment]
sure will have a look at it asap

**Comment by Eljoy** [comment]
@zdh-github version 1.6.0 has been released which should address the issue

**Comment by zdh-github** [comment]
Thanks! you are so awesome
